services:
  - type: web
    name: masters-live-scoreboard
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: REFRESH_SECONDS
        value: 60
